"""
Shared constants and data schemas for the pipeline compatibility layer.

All outputs generated by these tools are labeled SYNTHETIC_COMPATIBILITY_ONLY
and must not be interpreted as clinical or performance evidence.
"""
from __future__ import annotations

SYNTHETIC_LABEL = "SYNTHETIC_COMPATIBILITY_ONLY"

ASSET_DISCLAIMER = (
    "This report only checks engineering readiness for running the existing pipeline. "
    "It does not validate ECG reconstruction performance, clinical utility, or "
    "diagnostic correctness."
)

COMPAT_DISCLAIMER = (
    "This is a synthetic compatibility and engineering smoke-test report only. "
    "It does not establish clinical validity, real ECG reconstruction accuracy, "
    "or diagnostic performance. All synthetic data is labeled SYNTHETIC_COMPATIBILITY_ONLY."
)

LEAD_NAMES = ["I", "II", "III", "aVR", "aVL", "aVF", "V1", "V2", "V3", "V4", "V5", "V6"]

REQUIRED_ASSETS = [
    {
        "path": "configs/runtime.default.yaml",
        "kind": "file",
        "role": "runtime configuration",
    },
    {
        "path": "configs/models.yaml",
        "kind": "file",
        "role": "model registry (checkpoint paths and roles)",
    },
    {
        "path": "models/best.pt",
        "kind": "file",
        "role": "YOLO lead detector checkpoint",
    },
    {
        "path": "models/best_model_effb3_phase9_ddp (2).pth",
        "kind": "file",
        "role": "primary EfficientNet-B3 segmentation checkpoint",
    },
    {
        "path": "models/best_model_phase10.pth",
        "kind": "file",
        "role": "fallback ResNet50 segmentation checkpoint",
    },
    {
        "path": "data/images",
        "kind": "directory",
        "role": "input ECG page images",
    },
    {
        "path": "data/test.csv",
        "kind": "file",
        "role": "test manifest (id column, optional fs column)",
    },
    {
        "path": "data/sample_submission.parquet",
        "kind": "file",
        "role": "submission template (id column, expected row order)",
    },
]

LARGE_FILE_SHA256_THRESHOLD_BYTES = 500 * 1024 * 1024
