"""
Generate a Markdown quality-control report for a waveform CSV.

This report is for engineering and research inspection only.
It does NOT constitute clinical ECG quality assessment.

Usage:
    python tools/quality/generate_quality_report.py \\
        --input benchmark_cases/seed/waveforms/case_000.csv \\
        --output reports/quality_report.md
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.quality.checks import (  # noqa: E402
    ENGINEERING_DISCLAIMER,
    CheckResult,
    load_waveform_csv,
    overall_severity,
    run_all_checks,
)

SEVERITY_ICONS = {
    "ok": "✅",
    "info": "ℹ️",
    "warning": "⚠️",
    "error": "❌",
}


def _icon(severity: str) -> str:
    return SEVERITY_ICONS.get(severity, "?")


def format_report(
    results: list[CheckResult],
    *,
    input_path: Path,
    parse_warnings: list[str],
) -> str:
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    overall = overall_severity(results)
    n_leads_info = next(
        (r.detail.get("found", "?") for r in results if r.name == "lead_count"), "?"
    )

    lines: list[str] = [
        "# ECG Waveform Quality-Control Report",
        "",
        f"> **DISCLAIMER:** {ENGINEERING_DISCLAIMER}",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Input file | `{input_path}` |",
        f"| Generated | {timestamp} |",
        f"| Leads found | {n_leads_info} |",
        f"| Overall status | {_icon(overall)} **{overall.upper()}** |",
        "",
        "---",
        "",
        "## Check Results",
        "",
        "| Check | Status | Message |",
        "|-------|--------|---------|",
    ]

    for result in results:
        icon = _icon(result.severity)
        status = f"{icon} {result.severity.upper()}"
        lines.append(f"| `{result.name}` | {status} | {result.message} |")

    lines += ["", "---", "", "## Detail", ""]

    for result in results:
        if not result.detail:
            continue
        lines.append(f"### `{result.name}`")
        lines.append("")
        for key, val in result.detail.items():
            if isinstance(val, dict):
                lines.append(f"**{key}:**")
                lines.append("")
                lines.append("| Lead | Value |")
                lines.append("|------|-------|")
                for k, v in sorted(val.items()):
                    lines.append(f"| {k} | {v} |")
                lines.append("")
            else:
                lines.append(f"- **{key}**: {val}")
        lines.append("")

    if parse_warnings:
        lines += ["---", "", "## Parse Warnings", ""]
        for warn in parse_warnings:
            lines.append(f"- {warn}")
        lines.append("")

    lines += [
        "---",
        "",
        "## Limitations",
        "",
        "- These checks are automated engineering heuristics only.",
        "- They do not replace expert ECG review.",
        "- Amplitude ranges assume millivolt-scale waveforms; confirm units before interpreting.",
        "- Flatline detection uses a fixed variance threshold and may produce false positives "
        "  on very low-amplitude physiological signals.",
        "",
        "_Generated by ECG Research Workbench QC tool._",
    ]

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a QC report for a waveform CSV (engineering/research use only)."
    )
    parser.add_argument("--input", required=True, help="Path to input waveform CSV.")
    parser.add_argument(
        "--output",
        default="reports/quality_report.md",
        help="Path for the output Markdown report.",
    )
    args = parser.parse_args(argv)

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}", file=sys.stderr)
        return 1

    print(f"[quality_report] Input  : {input_path}")
    print(f"[quality_report] Output : {output_path}")

    leads, parse_warnings = load_waveform_csv(input_path)
    results = run_all_checks(leads)
    overall = overall_severity(results)

    report = format_report(results, input_path=input_path, parse_warnings=parse_warnings)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")

    print(f"\n[quality_report] Overall status : {overall.upper()}")
    for result in results:
        icon = {"ok": "OK", "info": "II", "warning": "!!", "error": "XX"}.get(
            result.severity, "??"
        )
        print(f"  [{icon}] {result.name}: {result.message}")
    print(f"\n[quality_report] Report written to: {output_path}")
    print(f"\n  DISCLAIMER: {ENGINEERING_DISCLAIMER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
